import type { Metadata } from "next";
import "./globals.css";
import Header from "./(components)/Header";
import Footer from "./(components)/Footer";
import AuthProvider from "./(components)/AuthProvider";
import ThemeRegistry from "@/theme/ThemeRegistry";

export const metadata: Metadata = {
  title: "All Out Organic | Love the life you live",
  description: "Generated by create next app with next-auth",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <ThemeRegistry>
          <body className="bg-gray-100">
            <Header />
            <div className="m-2">{children}</div>
            <Footer />
          </body>
        </ThemeRegistry>
      </AuthProvider>
    </html>
  );
}
