import type { Metadata } from "next";
import "./globals.css";
import Nav from "./Components/Header";
import AuthProvider from "./Components/AuthProvider";
import ThemeRegistry from "@/theme/ThemeRegistry";

export const metadata: Metadata = {
  title: "Next Auth Setup",
  description: "Generated by create next app with next-auth",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <ThemeRegistry>
          <body className="bg-gray-100">
            <Nav />
            <div className="m-2">{children}</div>
          </body>
        </ThemeRegistry>
      </AuthProvider>
    </html>
  );
}
